### ISSUE TITLE
Not so big double values are not correct

### ISSUE THREAD

**Issue by StefanBelo** [rpgmaker/NetJSON#68]
From JSON 16670245.64 the value is parsed as 1.6.

Added: Just debugging the code, and json is "1.721086399E7", so your algorithm does no process e7

**Comment by rpgmaker** [comment]
Yes. It does not. I will update it, but in the meantime you can update the methods to call .net version  of it. I might just have methods intercept for such cases.

**Comment by rpgmaker** [comment]
We're you able to temporarily make a change to allow processing of float with E?

**Comment by StefanBelo** [comment]
Yes, as you suggested. 

I browsed your code for floating point numbers parsing, when parsing floating point numbers you have got number before point (I am not native English speaking so I hope you know what I want to say.) , after point, and exponent that number after E. 

If those three numbers would be parsed like integers, it would not be applied problem with rounding, and multiplying should be quicker as would not be done by floating point multiplying. Only at the end of parsing you would apply 2 floating point multiplications.

When parsing floating point number after point, you will have to count exponent position, so for instance:

123.45e7

123
45 (count 2 point numbers)
7

(123 + (45 * 10^-2)) * (10^7)

**Comment by rpgmaker** [comment]
Can you confirm if this fixes the issue with double/decimal? If it does then i can apply it to float also

**Comment by StefanBelo** [comment]
Thanks for your hard work, but.. 

Even float number can be in JSON represented by 3.40282347e+38f, you implement "E calculation" only for double.

All floating point numbers parsing algorithm have problems with floating number rounding problem, I described in the issue:

https://github.com/rpgmaker/NetJSON/issues/67

So the parsing algorithm should be implemented with decimal number precision as with decimal calculation such problem does not occur.

Then your FastStringToDouble, FastStringToFloat should use FastStringToDecimal, and cast result to double and float.

Did you consider my advice to treat floating point numbers parsing algorithm like separate long/int numbers parsing with end result as:

(123 + (45 * 10^-2)) * (10^7)

float or double representation when transferred to string, for big number is always represented with exponent, for instance, float number:

111111111111111111111111111111.12

in string/text:

1.111111111e+29

of course it losses precision in string, and you can see that actually all parts of such number could be represented by int (I mean in 32 bit representation). I think there is performance difference in longlong numbers calculations to long/int
 
Your library is all about speed/performance, when I reported problem with floating number rounding problem, you said decimal calculation take more time, and that is clear as decimal works with precision in calculation and representation (in string), and that is the main goal for this type/object.

My app uses rest api only with double numbers, so it works for me, but will not work in general usage for others who use different floating point numbers in json.

**Comment by StefanBelo** [comment]
I am sorry I replied before testing new code of yours, there is a never ending loop somewhere in the code.

**Comment by StefanBelo** [comment]
Well, it seems to be quite mysterious problem. Your new code does not work with login response data in my app, but when testing within your solution, it works. I have been forced to use old library of yours, thanks god I did not delete it as I did with your old library code. I will try to investigate this problem during this weekend. 

Please, consider to revisit what I said in 2 posts above.

**Comment by rpgmaker** [comment]
At this point I did not implement the logic for float because I wanted you to verify that it works for the other type.

As the infinite loop, it might be because I did not check for e+ or e-. I will update the logic for it. And by the way I did use the formula that you gave me except my precision is somewhat off because of not casting to int/long during the calculation.

**Comment by rpgmaker** [comment]
Can you give me a sample payload that is failing and getting the infinite loop?

Thanks

**Comment by StefanBelo** [comment]
I am about to leave home in 40 minutes, I am from Slovakia, and we play ice hockey matches two times in week. I will send you problematic data this weekend.

And for floating point parsing algorithm. Yes, but instead of int, for floating points you work with exact type, so with float or double.
If you do only with ints:

sign = 1 or -1

(sign) * (123 + (decimal)(45 * 10^-2)) * (10^7)

all above operations could be int values, and only final result will be casted to decimal

**Comment by rpgmaker** [comment]
That is fine. I can work with that.

Thanks,

**Comment by JohanLindvall** [comment]
Can exception handling also be added to the numeric parsing code so that illegal numbers are detected and signaled with exceptions?

**Comment by rpgmaker** [comment]
I created one a long time ago for it. Which I plan to work on soon.https://github.com/rpgmaker/NetJSON/issues/61

**Comment by JohanLindvall** [comment]
Yes, but please note that the way numeric values are parsed right now can give incorrect results silently.

**Comment by rpgmaker** [comment]
I  will look into testing it thanks

**Comment by StefanBelo** [comment]
I have just started debugging your latest code, for this JSON:

{"token":"RuJ/+B4925OCm++9rw8vacX1UazQl4PGoRnMdyEKNBQ=","product":"WaIiEmhVft0FXzxr","status":"SUCCESS","error":""}

SkipProperty throws exception.

**Comment by StefanBelo** [comment]
Maybe skipping "error" property when ""

**Comment by StefanBelo** [comment]
And that was a luck with above json data as for other attempts app frozen at 

let data = NetJSON.Deserialize<BaseApiResponse>(responseBody)

in infinite loop without throwing exception.

**Comment by rpgmaker** [comment]
Interesting. I thought I fixed this issue a long time ago.  Cab you create a separate issue for it?

Thanks,

**Comment by rpgmaker** [comment]
What happens if you remove error property from the json?

**Comment by StefanBelo** [comment]
This is really quite strange. I will try to explain everything as I or you are still missing something. 

My app is written in F# only UI parts, well basically only WPF xaml and some small code behind is in C#, all together solution contains more than 32 projects.

The solution is built for .net 4.5.2, I used your previous version 1.0.7 where by default I changed:

_useEnumString = true
_dateFormat = NetJSONDateFormat.ISO

I reported problems with floating point rounding, so in FastStringToDouble I changed all variables from double to decimal, and result is casted to double.

Two days ago you asked me test your latest code. I download the source and made fatal mistake not saving the previous code, I changed 

_useEnumString = true
_dateFormat = NetJSONDateFormat.ISO

and leaving your code for FastStringToDouble  intact. I wanted to test if really your solution will fix floating point rounding problem, well yes you added the code to process Ee in double string number representation.

Well, first I tested only your solution, floating point number problem still exist, as it is actually not a problem in your implementation but how not precise float and double calculations are implemented, you can test it yourself:
```C#
        public void TestSNDouble() {
            var value = "1.14";
            var dValue = NetJSON.FastStringToDouble(value);
        }
```
dValue will not be 1.14 but 1.1400000000000001

This problem will be solved only when you do as I did some replace any calculation to decimal and then casting result to float or double.

Or to optimize it, do what I suggested to replace all multiplication with int/long version and do last calculation in decimal operations:

(sign) * (123 + (decimal)(45 * 10^-2)) * (10^7)

Then I moved your project to my solution, and in first json deserialization when my app login to rest api of data provider, the 

```F#
let data = NetJSON.Deserialize<BaseApiResponse>(responseBody)
```
locks in infinite loop. What is strange when taking response data and test them in your solution all works. What is a difference? The same code running correctly in your solution, but not in mine.

When I replace all version, well I have only assembly, then all works again.

The response json object contains 4 properties, all string, so I added breakpoint to your DecodeJSONString

when clicking through code debugging, the first property value processed by DecodeJSONString is

```json
{"token":"RuJ/+B4925OCm++9rw8vacX1UazQl4PGoRnMdEKNBQ=","product":"productxxxx","status":"SUCCESS","error":""}
```

is product property, not token. Is this a problem, and why old code assembly works in my project but not new one?

Are there difference in order of properties when built in my solution, and when built in yours, well it seems they are but why?

**Comment by rpgmaker** [comment]
I have not changed how property are been processed from the beginning. It always reads from left to right as the json is presented. The only possible reason yours might be getting infinite is because yours does not the fix from a long time ago that fixed issue with string skipping infinite loop. You submitted it https://github.com/rpgmaker/NetJSON/issues/58

**Comment by rpgmaker** [comment]
I fixed the issue with scenarios such as "1.41" been converted to run value. I also added support for E- and E+
Fix is here:  https://github.com/rpgmaker/NetJSON/commit/cebc2a77a4bf067d5d395e72d9cf40116893a967
Can you review it to see if it does what you requested. And btw, In making the changes you suggested I did not get the correct value for "e+29" example you gave. In fact, when i tested it online with some calculator the result differ from what you gave me.

Thanks,

**Comment by rpgmaker** [comment]
I am closing this seen I believe I fixed the issue already with the incorrect precision and also issue with using E/e +/-

You can open a new issue for it, if it is not still resolved. As the infinite loop issue please a new issue if you are able to reproduce it with the current code.

Thanks,

**Comment by StefanBelo** [comment]
Please watch this video from debugging your code:

https://www.youtube.com/watch?v=5N_DNDsueU0

JSON response length is 115 chars. JSON data contains just string values, 4 properties. Skip to 1:02 time of my video, and then watch index variable 6975, json data length is only 115 chars. 

There is some strange problem in your code.

**Comment by StefanBelo** [comment]
This one:
} else if (count == 0 && current == 'n') {

meant to be:
} else if (count == 0 && current == '\n') {

**Comment by rpgmaker** [comment]
This logic check for null where the first character is n. It is not
checking new line

**Comment by StefanBelo** [comment]
ok, you browse memory pointer, so char is actually Unicode UTF8, so two bytes?

**Comment by StefanBelo** [comment]
```json
{"token":"RuJ/+B4925OCm++9rw8vacX1UazQl4PGoRnMdEKNBQ=","product":"productxxxx","status":"SUCCESS","error":""}
```
JSN have 4 string parameter values, when debugging:

token is read, but cannot see product, then status is correctly read, then code goes out of memory, index 6975, data length is only 157.

My data object declares properties in exact order as seen in JSON, so why product is not read?

**Comment by rpgmaker** [comment]
Paste the class and the payload that fail.for me to test it and what cause
it.

**Comment by StefanBelo** [comment]
well, that is problem. You already have json data, and when tested on data sample all is parsed correctly, but not in project live code as you can see in my video.

**Comment by rpgmaker** [comment]
Are you using the latest code? I fixed the skipping issue not too long ago.

https://github.com/rpgmaker/NetJSON/issues/69

**Comment by StefanBelo** [comment]
Your old library, unfortunately as I said, I do not have source code just built assembly, that old assembly works, but not new one.

**Comment by StefanBelo** [comment]
Yes, I believe I use the latest code.

**Comment by StefanBelo** [comment]
Last time I downloaded when you said you corrected e/E problem.

**Comment by rpgmaker** [comment]
I will look into it

**Comment by StefanBelo** [comment]
Please for testing add to your solution F# console app project, add reference to you library and replace it with this code to test:
```F#
open NetJSON

[<CLIMutable; NoEquality; NoComparison>]
type BaseApiResponse =
    {
        token : string
        product : string
        status : string
        error : string
    }

    member this.IsSuccess
        with get() = this.status = "SUCCESS"

[<EntryPoint>]
let main argv = 
    
    let jsonData = """{"token":"sFdDNKjLPZJSm0+gvsD1PsksJd3YzbbsClttbWLWz50=","product":"productblabla","status":"SUCCESS","error":""}"""

    let data = NetJSON.Deserialize<BaseApiResponse>(jsonData)

    printf "%A" data
    0
```
When you debug the same experience as you can see in my video. Only product property will be set in this case, well no pointer overflow in this case but data were not parse correctly.

When I add the same code to your unit test project:

```C#
        [TestMethod]
        public void StringSkippingCauseInfiniteLoop2()
        {
            string jsonData = "{\"token\":\"sFdDNKjLPZJSm0+gvsD1PsksJd3YzbbsClttbWLWz50=\",\"product\":\"productblabla\",\"status\":\"SUCCESS\",\"error\":\"\"}";

            var data = NetJSON.Deserialize<BaseApiResponse>(jsonData);
        }
```
and if I use assembly compiled in F# then test in C# ends in infinite loop. It means there is some problem how F# code is compiled to .net assembly, and how your code treats it. In your previous library there was no such problem.

This F# code for my data object/type:

```F#
namespace FsharpData

[<CLIMutable; NoEquality; NoComparison>]
type BaseApiResponse =
    {
        token : string
        product : string
        status : string
        error : string
    }

    member this.IsSuccess
        with get() = this.status = "SUCCESS"
```

is compiled to C# representation:

```C#
using Microsoft.FSharp.Core;
using System;
using System.Diagnostics;
namespace FsharpData
{
	[CLIMutable, CompilationMapping(SourceConstructFlags.RecordType), NoComparison, NoEquality]
	[Serializable]
	public sealed class BaseApiResponse
	{
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		internal string token@;
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		internal string product@;
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		internal string status@;
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		internal string error@;
		[CompilationMapping(SourceConstructFlags.Field, 0)]
		public string token
		{
			get
			{
				return this.token@;
			}
			set
			{
				this.token@ = value;
			}
		}
		[CompilationMapping(SourceConstructFlags.Field, 1)]
		public string product
		{
			get
			{
				return this.product@;
			}
			set
			{
				this.product@ = value;
			}
		}
		[CompilationMapping(SourceConstructFlags.Field, 2)]
		public string status
		{
			get
			{
				return this.status@;
			}
			set
			{
				this.status@ = value;
			}
		}
		[CompilationMapping(SourceConstructFlags.Field, 3)]
		public string error
		{
			get
			{
				return this.error@;
			}
			set
			{
				this.error@ = value;
			}
		}
		public bool IsSuccess
		{
			get
			{
				return string.Equals(this.status@, "SUCCESS");
			}
		}
		public BaseApiResponse(string token, string product, string status, string error)
		{
			this.token@ = token;
			this.product@ = product;
			this.status@ = status;
			this.error@ = error;
		}
		public BaseApiResponse()
		{
		}
	}
}
```
I cannot see any problem in such object representation, well in source code you would write through property getters/setters without using internal data, but actually .net do the same for you.

Well this attribute on properties:

[CompilationMapping(SourceConstructFlags.Field, 3)]

just keeps order of properties.

**Comment by StefanBelo** [comment]
Your latest code, plus my test addition to unit test, and 2 F# projects, one data sample, and the other project the console app. Please download for your testing from this url:

http://bfexplorer.net/Content/Downloads/NetJSON-master.zip

**Comment by rpgmaker** [comment]
Thanks. I will try it out.

**Comment by rpgmaker** [comment]
Can you repost it as a new issue since it unrelated to this issue we are currently posting in?

Thanks,
